
package com.samenea.seapay.client.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "seapayGatewayService", targetNamespace = "http://service.transaction.seapay.samenea.com/", wsdlLocation = "http://localhost:8181/web/services/SeapayGatewayService?wsdl")
public class SeapayGatewayService
    extends Service
{

    private final static URL SEAPAYGATEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEAPAYGATEWAYSERVICE_EXCEPTION;
    private final static QName SEAPAYGATEWAYSERVICE_QNAME = new QName("http://service.transaction.seapay.samenea.com/", "seapayGatewayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8181/web/services/SeapayGatewayService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEAPAYGATEWAYSERVICE_WSDL_LOCATION = url;
        SEAPAYGATEWAYSERVICE_EXCEPTION = e;
    }

    public SeapayGatewayService() {
        super(__getWsdlLocation(), SEAPAYGATEWAYSERVICE_QNAME);
    }

    public SeapayGatewayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEAPAYGATEWAYSERVICE_QNAME, features);
    }

    public SeapayGatewayService(URL wsdlLocation) {
        super(wsdlLocation, SEAPAYGATEWAYSERVICE_QNAME);
    }

    public SeapayGatewayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEAPAYGATEWAYSERVICE_QNAME, features);
    }

    public SeapayGatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeapayGatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISeapayGatewayService
     */
    @WebEndpoint(name = "SeapayGatewayServicePort")
    public ISeapayGatewayService getSeapayGatewayServicePort() {
        return super.getPort(new QName("http://service.transaction.seapay.samenea.com/", "SeapayGatewayServicePort"), ISeapayGatewayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISeapayGatewayService
     */
    @WebEndpoint(name = "SeapayGatewayServicePort")
    public ISeapayGatewayService getSeapayGatewayServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.transaction.seapay.samenea.com/", "SeapayGatewayServicePort"), ISeapayGatewayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEAPAYGATEWAYSERVICE_EXCEPTION!= null) {
            throw SEAPAYGATEWAYSERVICE_EXCEPTION;
        }
        return SEAPAYGATEWAYSERVICE_WSDL_LOCATION;
    }

}
